var Items = Backbone.Model.extend({
    defaults: {
        id: '',
        description: '',
        type: '',
        price: '',
        priceLevel1: '',
        productLine: null,
        priceLevel2: '',
        priceLevel3: '',
        priceLevel4: '',
        priceLevel5: '',
        choiceGroup: 0,
        altDescription: '',
        category: 0,
        salesAccount: 0,
        allowDiscount: false,
        isStock: false,
        inactive: false,
        scale: false,
        serialized: false,
        noPartialQuantity: false,
        vatCode: 0,
        taxable: true,
        onHand: 0,
        trackAvailableOption: 0,
        warnAvailableNumber: 0,
    }
});